#!/bin/bash

#probably this would deploy code to child servers
#by running git-pull over ssh or something
#but for now just start the servers on the same
#system as concrete
echo "Build worked. Launching services."
at now + 0 min -f launchservices
echo "Service launched."
