#!/bin/bash
sudo -u ubuntu
cat >init2 <<EOL
#!/bin/bash
cd /home/ubuntu
echo "Hello from init script." > /home/ubuntu/hello
/usr/bin/git clone git://github.com/ithkuil/ls.git
cd ls
npm install
echo "cd and npm install ok " >> /home/ubuntu/hello
git config --add concrete.runner 'npm test | coffee sesreport.coffee'
echo "git config ok " >> /home/ubuntu/hello
/usr/bin/concrete . >>/home/ubuntu/hello 2>&1 &
echo "concrete ran ok " >> /home/ubuntu/hello
sleep 5
wget http://localhost:4567
set -e
npm test | coffee sesreport.coffee
./build-worked
EOL
chown ubuntu init2
chmod uga+x init2
sudo -u ubuntu ./init2